### ISSUE TITLE
NullPointerException: uriString

### ISSUE THREAD

**Issue by lingling-fan** [mofosyne/tagdrop#17]
//package name: com.github.mofosyne.tagdrop
//version: 1.0
//target sdk version: android-18
 java.lang.IllegalStateException: Could not execute method of the activity
 	at android.view.View$1.onClick(View.java:3633)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View$PerformClick.run(View.java:17721)
 	at android.os.Handler.handleCallback(Handler.java:730)
 	at android.os.Handler.dispatchMessage(Handler.java:92)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.reflect.InvocationTargetException
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at android.view.View$1.onClick(View.java:3628)
 Caused by: java.lang.NullPointerException: uriString
 	at android.net.Uri$StringUri.<init>(Uri.java:468)
 	at android.net.Uri$StringUri.<init>(Uri.java:458)
 	at android.net.Uri.parse(Uri.java:430)
 	at com.github.mofosyne.tagdrop.main.openWebPage(main.java:89)
 	at com.github.mofosyne.tagdrop.main.launchContent(main.java:84)

**Comment by mofosyne** [comment]
Thanks mate. I hope to revisit this project one day. 

One particular issues is I need to work out a way to embed a proper QR code library to this app, in such a way that it does not require an extra external depedency (like google play). This is since this is also distributed in F-Droid which only allow opensource apps.

But if you are interesting in tackling this together, or got some advice, I'm all ears.

**Comment by mofosyne** [comment]
did a massive revamp of this code base, so this error is most likely outdated now.
